In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10,3.9)

array([3.9, 3.9, 3.9, 3.9, 3.9, 3.9, 3.9, 3.9, 3.9, 3.9])

In [5]:
a=np.array([1,2,3,4])
a
a[2]

np.int64(3)

In [6]:
a[2] = 10
a

array([ 1,  2, 10,  4])

In [7]:
np.arange(3,100)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
       71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87,
       88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [8]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [9]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
n = np.array([[1,2,3],[10,20,30],[100,200,300]])

n[0, 2] = 9
print(n)
print("\n")
print(n[1])

print("\n")

print(n[:, 1])
print("\n")
n[:,1] = [900,901,902]
print(n)

[[  1   2   9]
 [ 10  20  30]
 [100 200 300]]


[10 20 30]


[  2  20 200]


[[  1 900   9]
 [ 10 901  30]
 [100 902 300]]


In [11]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [12]:
np.random.randn(10,2)

array([[ 0.55145404,  2.29220801],
       [ 0.04153939, -1.11792545],
       [ 0.53905832, -0.5961597 ],
       [-0.0191305 ,  1.17500122],
       [-0.74787095,  0.00902525],
       [-0.87810789, -0.15643417],
       [ 0.25657045, -0.98877905],
       [-0.33882197, -0.23618403],
       [-0.63765501, -1.18761229],
       [-1.42121723, -0.1534952 ]])

In [13]:
np.random.seed(2)
np.random.randint(low=9,high=100,size=(5,3))

array([[49, 24, 81],
       [31, 52, 91],
       [84, 16, 43],
       [58, 84, 94],
       [56, 72, 40]])

In [15]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [20]:
a+1
b=(10+(a*2))**2/100

In [21]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [22]:
 a > b 

array([False, False,  True,  True,  True])

In [23]:
a[a>b]

array([2, 3, 4])

In [25]:
print(a.max())

4
